if not loadStatFile then
	dofile("statdesc.lua")
end
loadStatFile("stat_descriptions.csd")

local out = io.open("../Data/ModScalability.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Item data (c) Grinding Gear Games\n\nreturn {\n')
for line, scalability in pairs(describeScalability("stat_descriptions.csd")) do
    out:write('\t["', line, '"] = { ')
    for i, scalable in ipairs(scalability) do
        out:write("{ isScalable = "..tostring(scalable.isScalable))
        if scalable.format then out:write(', format = "'..scalable.format..'"') end
        out:write(" }")
        if i < #scalability then out:write(", ") end
    end
    out:write(" },\n")
end

out:write('}')
out:close()

print("Stat mod scalability exported.")
