-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Dull Hatchet"] = {
	class = "One Hand Axe",
	category = "One Hand Axe",
	quality = 20,
	socketLimit = 2,
	tags = { axe = true, onehand = true, ezomyte_basetype = true, weapon = true, one_hand_weapon = true, default = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 4, PhysicalMax = 10, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { },
}
