-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Golden Obi"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	tags = { demigods = true, not_for_sale = true, default = true, belt = true, },
	implicit = "(20-30)% increased Rarity of Items found",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Rawhide Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "(20-30)% increased Life Recovery from Flasks",
	implicitModTypes = { { "flask", "resource", "life" }, },
	req = { },
}
itemBases["Linen Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "(20-30)% increased Mana Recovery from Flasks",
	implicitModTypes = { { "flask", "resource", "mana" }, },
	req = { },
}
itemBases["Wide Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "(20-30)% increased Flask Charges gained",
	implicitModTypes = { { "flask" }, },
	req = { level = 14, },
}
itemBases["Long Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "(15-20)% increased Charm Effect Duration",
	implicitModTypes = { {  }, },
	req = { level = 20, },
}
itemBases["Plate Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "+(100-140) to Armour",
	implicitModTypes = { { "armour", "defences" }, },
	req = { level = 24, },
}
itemBases["Ornate Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "(10-15)% reduced Charm Charges used",
	implicitModTypes = { {  }, },
	req = { level = 31, },
}
itemBases["Mail Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "(10-15)% reduced Flask Charges used",
	implicitModTypes = { { "flask" }, },
	req = { level = 40, },
}
itemBases["Double Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "(20-30)% increased Charm Charges gained",
	implicitModTypes = { {  }, },
	req = { level = 44, },
}
itemBases["Heavy Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "(20-30)% increased Stun Threshold",
	implicitModTypes = { {  }, },
	req = { level = 50, },
}
itemBases["Utility Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "20% of Flask Recovery applied Instantly",
	implicitModTypes = { {  }, },
	req = { level = 55, },
}
itemBases["Fine Belt"] = {
	class = "Belt",
	category = "Belt",
	label = "Belt",
	charmLimit = 1,
	tags = { belt = true, default = true, },
	implicit = "Flasks gain 0.17 charges per Second",
	implicitModTypes = { {  }, },
	req = { level = 62, },
}
