-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Rattling Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
itemBases["Stoic Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Discipline",
	implicitModTypes = { },
	req = { },
}
itemBases["Lupine Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
itemBases["Omen Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Malice",
	implicitModTypes = { },
	req = { },
}
itemBases["Ochre Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
itemBases["Shrine Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Fire",
	implicitModTypes = { },
	req = { },
}
itemBases["Shrine Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Ice",
	implicitModTypes = { },
	req = { },
}
itemBases["Shrine Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Lightning",
	implicitModTypes = { },
	req = { },
}
itemBases["Devouring Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
itemBases["Clasped Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
itemBases["Devotional Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
itemBases["Wrath Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
itemBases["Aromatic Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
itemBases["Pious Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
itemBases["Hallowed Sceptre"] = {
	class = "Sceptre",
	category = "Sceptre",
	label = "Sceptre",
	quality = 20,
	spirit = 100,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior",
	implicitModTypes = { },
	req = { },
}
