-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Withered Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Bone Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Attuned Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { default = true, onehand = true, wand = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Siphoning Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { default = true, onehand = true, wand = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Volatile Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { no_physical_spell_mods = true, onehand = true, no_cold_spell_mods = true, wand = true, no_lightning_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Galvanic Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_physical_spell_mods = true, no_cold_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Acrid Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { default = true, onehand = true, wand = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Offering Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Frigid Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_physical_spell_mods = true, no_lightning_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Torture Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { default = true, onehand = true, wand = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Critical Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { default = true, onehand = true, wand = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Primordial Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Dueling Wand"] = {
	type = "Wand",
	socketLimit = 2,
	tags = { default = true, onehand = true, wand = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Random Wand"] = {
	type = "Wand",
	hidden = true,
	socketLimit = 2,
	tags = { wand = true, default = true, },
	implicitModTypes = { },
	req = { },
}
