-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Withered Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, default = true, },
	implicit = "Grants Skill: Level (1-20) Chaos Bolt",
	implicitModTypes = { },
	req = { },
}
itemBases["Bone Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicit = "Grants Skill: Level (1-20) Bone Blast",
	implicitModTypes = { },
	req = { },
}
itemBases["Attuned Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Mana Drain",
	implicitModTypes = { },
	req = { },
}
itemBases["Siphoning Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Power Siphon",
	implicitModTypes = { },
	req = { },
}
itemBases["Volatile Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { no_physical_spell_mods = true, onehand = true, no_cold_spell_mods = true, wand = true, no_lightning_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicit = "Grants Skill: Level (1-20) Volatile Dead",
	implicitModTypes = { },
	req = { },
}
itemBases["Galvanic Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_physical_spell_mods = true, no_cold_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicit = "Grants Skill: Level (1-20) Galvanic Field",
	implicitModTypes = { },
	req = { },
}
itemBases["Acrid Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Decompose",
	implicitModTypes = { },
	req = { },
}
itemBases["Offering Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicit = "Grants Skill: Level (1-20) Exsanguinate",
	implicitModTypes = { },
	req = { },
}
itemBases["Frigid Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_physical_spell_mods = true, no_lightning_spell_mods = true, no_chaos_spell_mods = true, default = true, },
	implicit = "Grants Skill: Level (1-20) Chaos Bolt",
	implicitModTypes = { },
	req = { },
}
itemBases["Torture Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Chaos Bolt",
	implicitModTypes = { },
	req = { },
}
itemBases["Critical Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Chaos Bolt",
	implicitModTypes = { },
	req = { },
}
itemBases["Primordial Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { no_fire_spell_mods = true, onehand = true, wand = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, default = true, },
	implicit = "Grants Skill: Level (1-20) Wither",
	implicitModTypes = { },
	req = { },
}
itemBases["Dueling Wand"] = {
	class = "Wand",
	category = "Wand",
	label = "Wand",
	quality = 20,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Chaos Bolt",
	implicitModTypes = { },
	req = { },
}
itemBases["Random Wand"] = {
	class = "HiddenItem",
	category = "",
	label = "Wand",
	hidden = true,
	tags = { wand = true, default = true, },
	implicitModTypes = { },
	req = { },
}
