-- This file is automatically generated, do not edit!
-- Stat data (c) Grinding Gear Games

return {
	["Enchant"] = {
	}, 
	["Explicit"] = {
		["1089_AllDamage"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_2154246560", 
				["text"] = "#% increased Damage", 
				["type"] = "explicit", 
			}, 
		}, 
		["1124_PhysicalDamagePercent"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1310194496", 
				["text"] = "#% increased Global Physical Damage", 
				["type"] = "explicit", 
			}, 
		}, 
		["1192_IncreasedBowDamageForJewel"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_4188894176", 
				["text"] = "#% increased Damage with Bows", 
				["type"] = "explicit", 
			}, 
		}, 
		["1279_BowIncreasedAccuracyRating"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_169946467", 
				["text"] = "#% increased Accuracy Rating with Bows", 
				["type"] = "explicit", 
			}, 
		}, 
		["1443_MaximumLifeOnKillPercent"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_2023107756", 
				["text"] = "Recover #% of Life on Kill", 
				["type"] = "explicit", 
			}, 
		}, 
		["1449_ManaGainedOnKillPercentage"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1030153674", 
				["text"] = "Recover #% of Mana on Kill", 
				["type"] = "explicit", 
			}, 
		}, 
		["1564_AreaOfEffect"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_280731498", 
				["text"] = "#% increased Area of Effect", 
				["type"] = "explicit", 
			}, 
		}, 
		["1579_SkillEffectDuration"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3377888098", 
				["text"] = "#% increased Skill Effect Duration", 
				["type"] = "explicit", 
			}, 
		}, 
		["2362_DamageRemovedFromManaBeforeLife"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_458438597", 
				["text"] = "#% of Damage is taken from Mana before Life", 
				["type"] = "explicit", 
			}, 
		}, 
		["2808_BaseChanceToPoison"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3885634897", 
				["text"] = "#% chance to Poison on Hit", 
				["type"] = "explicit", 
			}, 
		}, 
		["4454_BleedDuration"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1459321413", 
				["text"] = "#% increased Bleeding Duration", 
				["type"] = "explicit", 
			}, 
		}, 
		["6796_FlaskGainChargePerMinute"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1873752457", 
				["text"] = "Gains # Charges per Second", 
				["type"] = "explicit", 
			}, 
		}, 
		["6817_JewelRadiusLargerRadius"] = {
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3891355829", 
				["text"] = "Upgrades Radius to Medium", 
				["type"] = "explicit", 
			}, 
		}, 
		["828_MovementVelocity"] = {
			["Boots"] = {
				["max"] = 35, 
				["min"] = 10, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_2250533757", 
				["text"] = "#% increased Movement Speed", 
				["type"] = "explicit", 
			}, 
		}, 
		["862_DamageWithBowSkills"] = {
			["Quiver"] = {
				["max"] = 59, 
				["min"] = 11, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1241625305", 
				["text"] = "#% increased Damage with Bow Skills", 
				["type"] = "explicit", 
			}, 
		}, 
		["871_IncreasedLife"] = {
			["Amulet"] = {
				["max"] = 149, 
				["min"] = 10, 
			}, 
			["Belt"] = {
				["max"] = 174, 
				["min"] = 10, 
			}, 
			["Boots"] = {
				["max"] = 149, 
				["min"] = 10, 
			}, 
			["Chest"] = {
				["max"] = 214, 
				["min"] = 10, 
			}, 
			["Gloves"] = {
				["max"] = 149, 
				["min"] = 10, 
			}, 
			["Helmet"] = {
				["max"] = 174, 
				["min"] = 10, 
			}, 
			["Ring"] = {
				["max"] = 119, 
				["min"] = 10, 
			}, 
			["Shield"] = {
				["max"] = 189, 
				["min"] = 10, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3299347043", 
				["text"] = "# to maximum Life", 
				["type"] = "explicit", 
			}, 
		}, 
		["871_LocalIncreasedArmourAndEnergyShieldAndLife"] = {
			["Boots"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Chest"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Gloves"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Helmet"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3299347043", 
				["text"] = "# to maximum Life", 
				["type"] = "explicit", 
			}, 
		}, 
		["871_LocalIncreasedArmourAndEvasionAndLife"] = {
			["Boots"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Chest"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Gloves"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Helmet"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3299347043", 
				["text"] = "# to maximum Life", 
				["type"] = "explicit", 
			}, 
		}, 
		["871_LocalIncreasedArmourAndLife"] = {
			["Boots"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Chest"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Gloves"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Helmet"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3299347043", 
				["text"] = "# to maximum Life", 
				["type"] = "explicit", 
			}, 
		}, 
		["871_LocalIncreasedEnergyShieldAndLife"] = {
			["Boots"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Chest"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Gloves"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Helmet"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3299347043", 
				["text"] = "# to maximum Life", 
				["type"] = "explicit", 
			}, 
		}, 
		["871_LocalIncreasedEvasionAndEnergyShieldAndLife"] = {
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3299347043", 
				["text"] = "# to maximum Life", 
				["type"] = "explicit", 
			}, 
		}, 
		["871_LocalIncreasedEvasionAndLife"] = {
			["Boots"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Chest"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Gloves"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["Helmet"] = {
				["max"] = 49, 
				["min"] = 7, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3299347043", 
				["text"] = "# to maximum Life", 
				["type"] = "explicit", 
			}, 
		}, 
		["872_MaximumLifeIncreasePercent"] = {
			["Amulet"] = {
				["max"] = 8, 
				["min"] = 3, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_983749596", 
				["text"] = "#% increased maximum Life", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_IncreasedMana"] = {
			["1HMace"] = {
				["max"] = 179, 
				["min"] = 10, 
			}, 
			["1HWeapon"] = {
				["max"] = 179, 
				["min"] = 10, 
			}, 
			["2HWeapon"] = {
				["max"] = 251, 
				["min"] = 14, 
			}, 
			["Amulet"] = {
				["max"] = 189, 
				["min"] = 10, 
			}, 
			["Belt"] = {
				["max"] = 179, 
				["min"] = 10, 
			}, 
			["Boots"] = {
				["max"] = 179, 
				["min"] = 10, 
			}, 
			["Focus"] = {
				["max"] = 179, 
				["min"] = 10, 
			}, 
			["Gloves"] = {
				["max"] = 179, 
				["min"] = 10, 
			}, 
			["Helmet"] = {
				["max"] = 179, 
				["min"] = 10, 
			}, 
			["Ring"] = {
				["max"] = 189, 
				["min"] = 10, 
			}, 
			["Shield"] = {
				["max"] = 179, 
				["min"] = 10, 
			}, 
			["Staff"] = {
				["max"] = 251, 
				["min"] = 14, 
			}, 
			["Wand"] = {
				["max"] = 179, 
				["min"] = 10, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_LocalIncreasedArmourAndEnergyShieldAndMana"] = {
			["Boots"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Chest"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Gloves"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Helmet"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_LocalIncreasedArmourAndEvasionAndMana"] = {
			["Boots"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Chest"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Gloves"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Helmet"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_LocalIncreasedArmourAndMana"] = {
			["Boots"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Chest"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Gloves"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Helmet"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_LocalIncreasedEnergyShieldAndMana"] = {
			["Boots"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Chest"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Gloves"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Helmet"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_LocalIncreasedEvasionAndEnergyShieldAndMana"] = {
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_LocalIncreasedEvasionAndMana"] = {
			["Boots"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Chest"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Gloves"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["Helmet"] = {
				["max"] = 39, 
				["min"] = 6, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_LocalIncreasedSpiritAndMana"] = {
			["1HMace"] = {
				["max"] = 45, 
				["min"] = 17, 
			}, 
			["1HWeapon"] = {
				["max"] = 45, 
				["min"] = 17, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_WeaponSpellDamageAndMana"] = {
			["1HWeapon"] = {
				["max"] = 45, 
				["min"] = 17, 
			}, 
			["2HWeapon"] = {
				["max"] = 64, 
				["min"] = 26, 
			}, 
			["Staff"] = {
				["max"] = 64, 
				["min"] = 26, 
			}, 
			["Wand"] = {
				["max"] = 45, 
				["min"] = 17, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["873_WeaponTrapDamageAndMana"] = {
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["874_MaximumManaIncreasePercent"] = {
			["Amulet"] = {
				["max"] = 10, 
				["min"] = 5, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_2748665614", 
				["text"] = "#% increased maximum Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["896_CharmGainLifeOnUse"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_2365392475", 
				["text"] = "Recover # Life when Used", 
				["type"] = "explicit", 
			}, 
		}, 
		["897_CharmGainManaOnUse"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1120862500", 
				["text"] = "Recover # Mana when Used", 
				["type"] = "explicit", 
			}, 
		}, 
		["898_CharmIncreasedDuration"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_2541588185", 
				["text"] = "#% increased Duration", 
				["type"] = "explicit", 
			}, 
		}, 
		["899_FlaskIncreasedRecoveryOnLowMana"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3276224428", 
				["text"] = "#% more Recovery if used while on Low Mana", 
				["type"] = "explicit", 
			}, 
		}, 
		["900_FlaskFullInstantRecovery"] = {
			["inverse"] = true, 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_700317374", 
				["text"] = "#% increased Amount Recovered", 
				["type"] = "explicit", 
			}, 
		}, 
		["900_FlaskIncreasedRecoveryAmount"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_700317374", 
				["text"] = "#% increased Amount Recovered", 
				["type"] = "explicit", 
			}, 
		}, 
		["903_FlaskExtraLifeCostsMana"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1261982764", 
				["text"] = "#% increased Life Recovered", 
				["type"] = "explicit", 
			}, 
		}, 
		["904_FlaskExtraManaCostsLife"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1811130680", 
				["text"] = "#% increased Mana Recovered", 
				["type"] = "explicit", 
			}, 
		}, 
		["905_FlaskHealsMinions"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_2416869319", 
				["text"] = "Grants #% of Life Recovery to Minions", 
				["type"] = "explicit", 
			}, 
		}, 
		["906_FlaskFullInstantRecovery"] = {
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1526933524", 
				["text"] = "Instant Recovery", 
				["type"] = "explicit", 
			}, 
		}, 
		["907_FlaskPartialInstantRecovery"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_2503377690", 
				["text"] = "#% of Recovery applied Instantly", 
				["type"] = "explicit", 
			}, 
		}, 
		["908_FlaskIncreasedRecoverySpeed"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_173226756", 
				["text"] = "#% increased Recovery rate", 
				["type"] = "explicit", 
			}, 
		}, 
		["9092_WeaponSwapSpeed"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3233599707", 
				["text"] = "#% increased Weapon Swap Speed", 
				["type"] = "explicit", 
			}, 
		}, 
		["909_FlaskExtraLifeCostsMana"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_648019518", 
				["text"] = "Removes #% of Life Recovered from Mana when used", 
				["type"] = "explicit", 
			}, 
		}, 
		["910_FlaskExtraManaCostsLife"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_959641748", 
				["text"] = "Removes #% of Mana Recovered from Life when used", 
				["type"] = "explicit", 
			}, 
		}, 
		["934_IncreasedCastSpeed"] = {
			["1HWeapon"] = {
				["max"] = 35, 
				["min"] = 9, 
			}, 
			["2HWeapon"] = {
				["max"] = 52, 
				["min"] = 14, 
			}, 
			["Amulet"] = {
				["max"] = 28, 
				["min"] = 9, 
			}, 
			["Focus"] = {
				["max"] = 32, 
				["min"] = 9, 
			}, 
			["Ring"] = {
				["max"] = 24, 
				["min"] = 9, 
			}, 
			["Shield"] = {
				["max"] = 32, 
				["min"] = 9, 
			}, 
			["Staff"] = {
				["max"] = 52, 
				["min"] = 14, 
			}, 
			["Wand"] = {
				["max"] = 35, 
				["min"] = 9, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_2891184298", 
				["text"] = "#% increased Cast Speed", 
				["type"] = "explicit", 
			}, 
		}, 
		["935_AdditionalAmmo"] = {
			["2HWeapon"] = {
				["max"] = 1, 
				["min"] = 1, 
			}, 
			["Crossbow"] = {
				["max"] = 1, 
				["min"] = 1, 
			}, 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1039380318", 
				["text"] = "Loads an additional bolt", 
				["type"] = "explicit", 
			}, 
		}, 
		["957_LifeRegeneration"] = {
			["Amulet"] = {
				["max"] = 33, 
				["min"] = 1, 
			}, 
			["Belt"] = {
				["max"] = 29, 
				["min"] = 1, 
			}, 
			["Boots"] = {
				["max"] = 23, 
				["min"] = 1, 
			}, 
			["Chest"] = {
				["max"] = 36, 
				["min"] = 1, 
			}, 
			["Helmet"] = {
				["max"] = 23, 
				["min"] = 1, 
			}, 
			["Ring"] = {
				["max"] = 18, 
				["min"] = 1, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3325883026", 
				["text"] = "# Life Regeneration per second", 
				["type"] = "explicit", 
			}, 
		}, 
		["958_LifeRegenerationRate"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_44972811", 
				["text"] = "#% increased Life Regeneration rate", 
				["type"] = "explicit", 
			}, 
		}, 
		["964_LifeGainedFromEnemyDeath"] = {
			["1HAxe"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["1HMace"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["1HSword"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["1HWeapon"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["2HAxe"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["2HMace"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["2HSword"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["2HWeapon"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["Bow"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["Claw"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["Dagger"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["Gloves"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["Quiver"] = {
				["max"] = 53, 
				["min"] = 4, 
			}, 
			["Ring"] = {
				["max"] = 53, 
				["min"] = 4, 
			}, 
			["Staff"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["Wand"] = {
				["max"] = 84, 
				["min"] = 4, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3695891184", 
				["text"] = "Gain # Life per Enemy Killed", 
				["type"] = "explicit", 
			}, 
		}, 
		["965_LightRadiusAndManaRegeneration"] = {
			["1HMace"] = {
				["max"] = 22, 
				["min"] = 8, 
			}, 
			["1HWeapon"] = {
				["max"] = 22, 
				["min"] = 8, 
			}, 
			["2HWeapon"] = {
				["max"] = 22, 
				["min"] = 8, 
			}, 
			["Ring"] = {
				["max"] = 22, 
				["min"] = 8, 
			}, 
			["Staff"] = {
				["max"] = 22, 
				["min"] = 8, 
			}, 
			["Wand"] = {
				["max"] = 22, 
				["min"] = 8, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_789117908", 
				["text"] = "#% increased Mana Regeneration Rate", 
				["type"] = "explicit", 
			}, 
		}, 
		["965_ManaRegeneration"] = {
			["1HMace"] = {
				["max"] = 69, 
				["min"] = 10, 
			}, 
			["1HWeapon"] = {
				["max"] = 69, 
				["min"] = 10, 
			}, 
			["2HWeapon"] = {
				["max"] = 69, 
				["min"] = 10, 
			}, 
			["Amulet"] = {
				["max"] = 69, 
				["min"] = 10, 
			}, 
			["Focus"] = {
				["max"] = 69, 
				["min"] = 10, 
			}, 
			["Ring"] = {
				["max"] = 69, 
				["min"] = 10, 
			}, 
			["Shield"] = {
				["max"] = 69, 
				["min"] = 10, 
			}, 
			["Staff"] = {
				["max"] = 69, 
				["min"] = 10, 
			}, 
			["Wand"] = {
				["max"] = 69, 
				["min"] = 10, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_789117908", 
				["text"] = "#% increased Mana Regeneration Rate", 
				["type"] = "explicit", 
			}, 
		}, 
		["969_ManaGainedFromEnemyDeath"] = {
			["1HAxe"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["1HMace"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["1HSword"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["1HWeapon"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["2HAxe"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["2HMace"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["2HSword"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["2HWeapon"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["Bow"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["Claw"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["Dagger"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["Gloves"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["Quiver"] = {
				["max"] = 27, 
				["min"] = 2, 
			}, 
			["Ring"] = {
				["max"] = 27, 
				["min"] = 2, 
			}, 
			["Staff"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["Wand"] = {
				["max"] = 45, 
				["min"] = 2, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1368271171", 
				["text"] = "Gain # Mana per Enemy Killed", 
				["type"] = "explicit", 
			}, 
		}, 
		["994_FlaskChanceRechargeOnKill"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_828533480", 
				["text"] = "#% Chance to gain a Charge when you Kill an Enemy", 
				["type"] = "explicit", 
			}, 
		}, 
		["995_FlaskIncreasedChargesAdded"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_3196823591", 
				["text"] = "#% increased Charges gained", 
				["type"] = "explicit", 
			}, 
		}, 
		["996_FlaskChargesUsed"] = {
			["inverse"] = true, 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_388617051", 
				["text"] = "#% increased Charges per use", 
				["type"] = "explicit", 
			}, 
		}, 
		["998_FlaskIncreasedMaxCharges"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "explicit.stat_1366840608", 
				["text"] = "#% increased Charges", 
				["type"] = "explicit", 
			}, 
		}, 
	}, 
	["Implicit"] = {
		["implicit.stat_1039380318_"] = {
			["2HWeapon"] = {
				["max"] = 1, 
				["min"] = 1, 
			}, 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_1039380318", 
				["text"] = "Loads an additional bolt", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_1050105434_"] = {
			["Ring"] = {
				["max"] = 30, 
				["min"] = 20, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_1050105434", 
				["text"] = "# to maximum Mana", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_1207554355_"] = {
			["Quiver"] = {
				["max"] = 30, 
				["min"] = 20, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_1207554355", 
				["text"] = "#% increased Arrow Speed", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_1803308202_"] = {
			["2HWeapon"] = {
				["max"] = 30, 
				["min"] = 20, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_1803308202", 
				["text"] = "#% increased Bolt Speed", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_2250533757_"] = {
			["Chest"] = {
				["max"] = 5, 
				["min"] = 5, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_2250533757", 
				["text"] = "#% increased Movement Speed", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_2891184298_"] = {
			["Ring"] = {
				["max"] = 10, 
				["min"] = 7, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_2891184298", 
				["text"] = "#% increased Cast Speed", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_3299347043_"] = {
			["Amulet"] = {
				["max"] = 40, 
				["min"] = 30, 
			}, 
			["Chest"] = {
				["max"] = 80, 
				["min"] = 60, 
			}, 
			["Gloves"] = {
				["max"] = 30, 
				["min"] = 20, 
			}, 
			["sign"] = "+", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_3299347043", 
				["text"] = "# to maximum Life", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_3325883026_"] = {
			["Amulet"] = {
				["max"] = 4, 
				["min"] = 2, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_3325883026", 
				["text"] = "# Life Regeneration per second", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_548198834_"] = {
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_548198834", 
				["text"] = "#% increased Range", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_789117908_"] = {
			["Amulet"] = {
				["max"] = 30, 
				["min"] = 20, 
			}, 
			["Chest"] = {
				["max"] = 50, 
				["min"] = 40, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_789117908", 
				["text"] = "#% increased Mana Regeneration Rate", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_836936635_"] = {
			["Chest"] = {
				["max"] = 2.5, 
				["min"] = 1.5, 
			}, 
			["sign"] = "", 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_836936635", 
				["text"] = "Regenerate #% of Life per second", 
				["type"] = "implicit", 
			}, 
		}, 
		["implicit.stat_958696139_"] = {
			["Ring"] = {
				["max"] = 1, 
				["min"] = 1, 
			}, 
			["specialCaseData"] = {
			}, 
			["tradeMod"] = {
				["id"] = "implicit.stat_958696139", 
				["text"] = "Grants 1 additional Skill Slot", 
				["type"] = "implicit", 
			}, 
		}, 
	}, 
	["Rune"] = {
	}, 
}